[meta]
Version = "0.1"

[[Motor]]
MotorNum = 7
MotorBrand = "Dongbu"
MotorModel = "DRS-0101"
JointName = "Sholder"
Bounds = [-150, 150]
AlignmentAngle = 0

[[Motor]]
MotorNum = 8
MotorBrand = "Dongbu"
MotorModel = "DRS-0101"
JointName = "Elbow"
Bounds = [-90, 90]
AlignmentAngle = 12
